In [1]:
import numpy as np
import astroquery
from astropy import units as u
from astroquery.simbad import Simbad
from astropy.coordinates import SkyCoord
import pandas as pd
from astropy.table import Table, vstack

In [19]:
radius=2.
df_2 = pd.read_csv('/home/nicolas/nico/Data/Masivas/Data_OB_stars/OBAGDR3.csv')

In [20]:
df_2 = df_2.head(100)

In [28]:
Simbad.TIMEOUT = 100000
Simbad.ROW_LIMIT = 0

In [29]:
Simbad.add_votable_fields('sptype')
Simbad.add_votable_fields('sp_bibcode')
coordinates = SkyCoord(df_2[["ra","dec"]].values,unit=("deg","deg"))
tabF = Simbad.query_region(coordinates, radius=radius*u.arcsec)

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): '16:13:09.49255593 -89:35:05.78253181': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 6 raised an error (recorded in the `errors` attribute of the result table): '10:35:11.3234973 -89:21:56.48757328': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 9 raised an error (recorded in the `errors` attribute of the result table): '1:51:26.53834491 -89:08:30.17130918': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 13 raised an error (recorded in the `errors` attribute of the result table): '17:44:27.71573107 -88:49:49.74295845': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 15 raised an error (recorded in the `errors` attribute of the result table): '13:53:57.70973673 -88:47:29.78042777': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 17 raised an error (recorded in the `errors` attribute of the result table): '8:24:06.58969133 -88:39:47.70756938': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 21 raised an error (recorded in the `errors` attribute of the result table): '10:28:28.15550606 -88:32:22.03048149': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 23 raised an error (recorded in the `errors` attribute of the result table): '22:25:06.10657393 -88:27:13.01322212': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 31 raised an error (recorded in the `errors` attribute of the result table): '0:57:32.86657139 -88:17:39.17304681': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 33 raised an error (recorded in the `errors` attribute of the result table): '19:51:12.21368864 -88:15:02.40731674': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 36 raised an error (recorded in the `errors` attribute of the result table): '9:14:49.90423876 -88:07:53.6303292': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 39 raised an error (recorded in the `errors` attribute of the result table): '8:31:50.92356521 -88:03:01.95200105': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 41 raised an error (recorded in the `errors` attribute of the result table): '5:13:33.60713674 -88:01:01.7048991': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 45 raised an error (recorded in the `errors` attribute of the result table): '17:53:25.55897241 -87:55:05.06094828': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 47 raised an error (recorded in the `errors` attribute of the result table): '19:34:20.99259778 -87:51:50.2626992': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 51 raised an error (recorded in the `errors` attribute of the result table): '7:49:14.01634942 -87:47:26.25636051': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 54 raised an error (recorded in the `errors` attribute of the result table): '12:49:32.00698462 -87:45:08.90920796': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 59 raised an error (recorded in the `errors` attribute of the result table): '4:34:00.34461221 -87:33:55.29244427': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 61 raised an error (recorded in the `errors` attribute of the result table): '20:26:28.55140265 -87:32:58.96554959': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 67 raised an error (recorded in the `errors` attribute of the result table): '11:02:38.37946708 -87:21:27.35111818': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 70 raised an error (recorded in the `errors` attribute of the result table): '10:57:01.17994168 -87:17:07.86453941': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 74 raised an error (recorded in the `errors` attribute of the result table): '9:38:48.80932934 -87:13:49.44146307': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 76 raised an error (recorded in the `errors` attribute of the result table): '7:38:25.84977632 -87:09:48.71250672': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 78 raised an error (recorded in the `errors` attribute of the result table): '11:57:37.54406416 -87:07:05.92895681': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 81 raised an error (recorded in the `errors` attribute of the result table): '14:12:18.43004626 -87:06:11.96035069': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 84 raised an error (recorded in the `errors` attribute of the result table): '18:32:05.19661033 -86:55:45.12869648': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 87 raised an error (recorded in the `errors` attribute of the result table): '23:40:08.78879213 -86:51:41.02807079': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 89 raised an error (recorded in the `errors` attribute of the result table): '4:26:39.08108331 -86:50:27.26727145': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 93 raised an error (recorded in the `errors` attribute of the result table): '18:12:30.76345516 -86:33:49.57019412': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 96 raised an error (recorded in the `errors` attribute of the result table): '1:41:13.00558649 -86:31:11.85401822': No astronomical object found :   [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 101 raised an error (recorded in the `errors` attribute of the result table): '0:14:22.33088368 -86:25:42.55307816': No astronomical object found :   [astroquery.simbad.core]

In [30]:
table=tabF.to_pandas()

In [31]:
table

,MAIN_ID,RA,DEC,RA_PREC,DEC_PREC,COO_ERR_MAJA,COO_ERR_MINA,COO_ERR_ANGLE,COO_QUAL,COO_WAVELENGTH,...,SP_BIBCODE_8,SP_TYPE_5,SP_QUAL_5,SP_BIBCODE_9,SP_BIBCODE_10,SP_TYPE_6,SP_QUAL_6,SP_BIBCODE_11,SP_BIBCODE_12,SCRIPT_NUMBER_ID
0,Gaia DR2 5188182749674777984,11 48 31.0247,-89 32 07.358,14,14,0.0267,0.0258,90,A,O,...,,,,,,,,,,2
1,Gaia DR3 6341129165091554304,21 28 26.1577,-89 09 42.951,14,14,0.0162,0.0161,90,A,O,...,,,,,,,,,,6
2,Gaia DR2 5188434091160619136,06 01 52.8146,-89 05 15.739,14,14,0.0185,0.0201,90,A,O,...,,,,,,,,,,9
3,* sig Oct,21 08 46.8635,-88 57 23.398,14,14,0.0516,0.0605,90,A,O,...,1975MSS...C01....0H,F0IV,C,1975MSS...C01....0H,1975MSS...C01....0H,F0IV,C,1975MSS...C01....0H,1975MSS...C01....0H,10
4,HD 108971,12 42 10.6916,-88 33 29.040,14,14,0.0435,0.0388,90,A,O,...,1975MSS...C01....0H,G0,E,1975MSS...C01....0H,1975MSS...C01....0H,G0,E,1975MSS...C01....0H,1975MSS...C01....0H,17
5,V* RW Oct,18 29 04.7062,-88 32 32.143,14,14,0.0108,0.0121,90,A,O,...,,,,,,,,,,18
6,TYC 9521-341-1,15 38 32.9741,-88 26 15.573,14,14,0.5431,0.5786,90,A,O,...,,,,,,,,,,22
7,Gaia DR2 5188570464962270336,08 53 13.3274,-88 26 09.852,14,14,0.0130,0.0132,90,A,O,...,,,,,,,,,,23
8,HD 1348,00 12 33.9573,-88 21 46.334,14,14,0.0196,0.0180,90,A,O,...,1975MSS...C01....0H,B9.5IV,C,1975MSS...C01....0H,1975MSS...C01....0H,B9.5IV,C,1975MSS...C01....0H,1975MSS...C01....0H,24
9,HD 16477,01 49 11.7717,-88 21 26.725,14,14,0.0339,0.0345,90,A,O,...,1975MSS...C01....0H,B9/9.5V,D,1975MSS...C01....0H,1975MSS...C01....0H,B9/9.5V,D,1975MSS...C01....0H,1975MSS...C01....0H,26
10,HD 224697,00 00 50.8881,-88 19 41.929,14,14,0.0227,0.0214,90,A,O,...,1975MSS...C01....0H,A4III,C,1975MSS...C01....0H,1975MSS...C01....0H,A4III,C,1975MSS...C01....0H,1975MSS...C01....0H,27
11,Gaia DR3 5765000499659503104,13 28 23.0863,-88 19 40.727,14,14,0.0185,0.0169,90,A,O,...,,,,,,,,,,28
12,Gaia DR3 4612037488488541312,02 26 03.9187,-88 13 23.435,14,14,0.0119,0.0110,90,A,O,...,,,,,,,,,,33
13,Gaia DR3 5188597574795907200,09 07 59.9583,-88 04 30.875,14,14,0.0168,0.0153,90,A,O,...,,,,,,,,,,36
14,TYC 9515-711-1,11 21 09.2243,-88 00 18.763,14,14,0.0102,0.0096,90,A,O,...,,,,,,,,,,40
15,TYC 9499-1413-1,02 06 16.683,-87 59 53.27,7,7,NaN,NaN,0,C,O,...,,,,,,,,,,41
16,Gaia DR3 6342250323354392320,19 16 39.3534,-87 49 37.541,14,14,0.0098,0.0105,90,A,O,...,,,,,,,,,,47
17,Gaia DR3 5765228854481604736,17 03 37.3379,-87 48 55.660,14,14,0.0124,0.0134,90,A,O,...,,,,,,,,,,48
18,2MASS J19430559-8746524,19 43 05.5805,-87 46 52.546,14,14,0.0125,0.0141,90,A,O,...,,,,,,,,,,50
19,Gaia DR2 6341738225813533568,22 48 44.8335,-87 43 10.184,14,14,0.0187,0.0209,90,A,O,...,,,,,,,,,,53
20,NSV 12754,20 28 37.4422,-87 43 05.747,14,14,0.0134,0.0135,90,A,O,...,,,,,,,,,,54
21,TYC 9533-320-1,22 13 24.8741,-87 39 30.359,14,14,0.0113,0.0125,90,A,O,...,,,,,,,,,,55
22,Gaia DR3 5765460267318737664,15 51 45.8746,-87 30 04.675,14,14,0.0166,0.0188,90,A,O,...,,,,,,,,,,61
23,EC 21086-8739,21 28 07.0677,-87 27 05.467,14,14,0.0143,0.0162,90,A,O,...,2013MNRAS.431..240O,sdB,D,2013MNRAS.431..240O,2013MNRAS.431..240O,sdB,D,2013MNRAS.431..240O,2013MNRAS.431..240O,62
24,UCAC4 013-003403,14 29 01.5030,-87 26 20.320,14,14,0.0621,0.0620,90,A,O,...,,,,,,,,,,63
25,TYC 9498-833-1,01 35 55.9931,-87 25 24.346,14,14,1.0117,0.9399,90,A,O,...,,,,,,,,,,64
26,TYC 9516-1134-1,12 16 38.2763,-87 19 04.291,14,14,0.1397,0.1313,90,A,O,...,,,,,,,,,,67
27,Gaia DR2 4613028423342541440,01 45 54.4724,-87 14 25.986,14,14,0.0216,0.0214,90,A,O,...,,,,,,,,,,70
28,HD 85742,09 29 13.1295,-87 14 12.887,14,14,0.0356,0.0351,90,A,O,...,1975MSS...C01....0H,B6III,C,1975MSS...C01....0H,1975MSS...C01....0H,B6III,C,1975MSS...C01....0H,1975MSS...C01....0H,71
29,Gaia DR2 5765928964213478656,14 24 03.7708,-87 06 52.292,14,14,0.0261,0.0274,90,A,O,...,,,,,,,,,,77
30,TYC 9531-658-1,19 31 49.7504,-86 58 06.174,14,14,0.8847,0.9550,90,C,O,...,,,,,,,,,,81
31,Gaia DR2 6342540079027881088,19 22 06.8345,-86 54 16.734,14,14,0.0181,0.0199,90,A,O,...,,,,,,,,,,83
32,CD-86 71,09 44 27.8214,-86 41 36.238,14,14,0.0191,0.0214,90,A,O,...,,,,,,,,,,89
33,Gaia DR3 6342467579979844352,20 25 21.5767,-86 37 02.131,14,14,0.0156,0.0162,90,A,O,...,,,,,,,,,,90
34,Gaia DR2 6345610499608144640,18 50 39.6387,-86 32 29.817,14,14,0.0112,0.0116,90,A,O,...,,,,,,,,,,93
35,Gaia DR2 5189735942990369792,07 55 04.3133,-86 30 42.550,14,14,0.0241,0.0268,90,A,O,...,,,,,,,,,,95
36,HD 86789,09 42 18.5076,-86 26 38.522,14,14,0.0106,0.0114,90,A,O,...,1975MSS...C01....0H,A0IV,C,1975MSS...C01....0H,1975MSS...C01....0H,A0IV,C,1975MSS...C01....0H,1975MSS...C01....0H,97
37,Gaia DR3 4614026470663041920,05 03 40.3048,-86 26 20.868,14,14,0.0137,0.0168,90,A,O,...,,,,,,,,,,98

In [63]:
table[table.duplicated(subset='SCRIPT_NUMBER_ID')==True]['SCRIPT_NUMBER_ID'].values

array([  22,   58,  106,  286,  323,  323,  426,  479,  479,  526,  597,
        597,  621,  621,  660,  805,  805,  854,  854,  921, 1094, 1165,
       1225, 1225, 1239, 1258, 1275, 1281, 1281, 1373, 1373, 1374, 1412,
       1804, 1804, 1852, 1852, 1868, 1868, 1942, 1942, 1975, 2125, 2173,
       2273, 2273, 2288, 2288, 2289, 2309, 2312, 2340, 2340, 2391, 2391,
       2431, 2578, 2578, 2633, 2651, 2661, 2670, 2683, 2683, 2728, 2728,
       2765, 2782, 2782, 2794, 2794, 2805, 2805, 2849, 2849, 2885, 2885,
       2948, 2948, 2957, 3020, 3020, 3023, 3023, 3066, 3066, 3144, 3146,
       3203, 3203, 3246, 3246, 3255, 3255, 3399, 3498, 3648, 3728, 3883,
       3923, 4013, 4072, 4101, 4101, 4164, 4164, 4181, 4181, 4219, 4219,
       4230, 4252, 4283, 4291, 4291, 4311, 4320, 4320, 4378, 4416, 4416,
       4450, 4530, 4578, 4602, 4623, 4623, 4649, 4800, 4914, 4914, 4961,
       5095, 5116, 5116, 5210, 5273, 5338, 5356, 5356, 5401, 5469, 5496,
       5521, 5601, 5687, 5746, 5753, 5762, 5820, 5820, 5844, 5976, 5976,
       6020, 6020], dtype=int32)

In [68]:
table[table['SCRIPT_NUMBER_ID']==22][['SP_TYPE','SP_BIBCODE']]

   SP_TYPE           SP_BIBCODE
21      F8  1993yCat.3135....0C
22

In [69]:
table[table['SCRIPT_NUMBER_ID']==58][['SP_TYPE','SP_BIBCODE']]

   SP_TYPE           SP_BIBCODE
58      G0  1993yCat.3135....0C
59

In [70]:
table[table['SCRIPT_NUMBER_ID']==106][['SP_TYPE','SP_BIBCODE']]

    SP_TYPE           SP_BIBCODE
107      A0  1993yCat.3135....0C
108

In [71]:
for i in table[table.duplicated(subset='SCRIPT_NUMBER_ID')==True]['SCRIPT_NUMBER_ID'].values:
    print(table[table['SCRIPT_NUMBER_ID']==i][['SP_TYPE','SP_BIBCODE']])

   SP_TYPE           SP_BIBCODE
21      F8  1993yCat.3135....0C
22
   SP_TYPE           SP_BIBCODE
58      G0  1993yCat.3135....0C
59
    SP_TYPE           SP_BIBCODE
107      A0  1993yCat.3135....0C
108
    SP_TYPE           SP_BIBCODE
288      A0  1993yCat.3135....0C
289      A0
    SP_TYPE           SP_BIBCODE
326      A0  1993yCat.3135....0C
327
328
    SP_TYPE           SP_BIBCODE
326      A0  1993yCat.3135....0C
327
328
    SP_TYPE           SP_BIBCODE
431      B8
432      B8  1993yCat.3135....0C
    SP_TYPE           SP_BIBCODE
485      K0  1995A&AS..110..367N
486
487
    SP_TYPE           SP_BIBCODE
485      K0  1995A&AS..110..367N
486
487
    SP_TYPE           SP_BIBCODE
534       A  1993yCat.3135....0C
535
    SP_TYPE           SP_BIBCODE
606       A  1995A&AS..110..367N
607
608
    SP_TYPE           SP_BIBCODE
606       A  1995A&AS..110..367N
607
608
    SP_TYPE           SP_BIBCODE
632      B9  1993yCat.3135....0C
633
634
    SP_TYPE           SP_BIBCODE
632      B9  1993yCat.3135....0C
633
634
    SP_TYPE           SP_BIBCODE
673      A0  1993yCat.3135....0C
674
    SP_TYPE           SP_BIBCODE
819      A2  1995A&AS..110..367N
820
821
    SP_TYPE           SP_BIBCODE
819      A2  1995A&AS..110..367N
820
821
    SP_TYPE           SP_BIBCODE
870      F0  1993yCat.3135....0C
871
872
    SP_TYPE           SP_BIBCODE
870      F0  1993yCat.3135....0C
871
872
    SP_TYPE           SP_BIBCODE
939      A0  1993yCat.3135....0C
940
     SP_TYPE           SP_BIBCODE
1113      A2  1993yCat.3135....0C
1114
     SP_TYPE           SP_BIBCODE
1185      A0  1993yCat.3135....0C
1186
     SP_TYPE           SP_BIBCODE
1246      B9  1995A&AS..110..367N
1247
1248
     SP_TYPE           SP_BIBCODE
1246      B9  1995A&AS..110..367N
1247
1248
     SP_TYPE           SP_BIBCODE
1262       F  1993yCat.3135....0C
1263
     SP_TYPE           SP_BIBCODE
1282      A3  1993yCat.3135....0C
1283
     SP_TYPE           SP_BIBCODE
1300      A0  1993yCat.3135....0C
1301
     SP_TYPE           SP_BIBCODE
1307      B9  1995A&AS..110..367N
1308
1309
     SP_TYPE           SP_BIBCODE
1307      B9  1995A&AS..110..367N
1308
1309
     SP_TYPE           SP_BIBCODE
1401      B8  1995A&AS..110..367N
1402
1403
     SP_TYPE           SP_BIBCODE
1401      B8  1995A&AS..110..367N
1402
1403
     SP_TYPE           SP_BIBCODE
1404      A0  1993yCat.3135....0C
1405
     SP_TYPE           SP_BIBCODE
1443      A3  1995A&AS..110..367N
1444
     SP_TYPE           SP_BIBCODE
1836      A3  1995A&AS..110..367N
1837
1838
     SP_TYPE           SP_BIBCODE
1836      A3  1995A&AS..110..367N
1837
1838
     SP_TYPE           SP_BIBCODE
1886  B9IV-V  2020A&A...640A..40H
1887
1888
     SP_TYPE           SP_BIBCODE
1886  B9IV-V  2020A&A...640A..40H
1887
1888
     SP_TYPE           SP_BIBCODE
1904      A3  1995A&AS..110..367N
1905
1906
     SP_TYPE           SP_BIBCODE
1904      A3  1995A&AS..110..367N
1905
1906
     SP_TYPE           SP_BIBCODE
1980      F0  1993yCat.3135....0C
1981
1982
     SP_TYPE           SP_BIBCODE
1980      F0  1993yCat.3135....0C
1981
1982
     SP_TYPE           SP_BIBCODE
2015      A0  1995A&AS..110..367N
2016
     SP_TYPE           SP_BIBCODE
2166      A2  1995A&AS..110..367N
2167
     SP_TYPE           SP_BIBCODE
2215      A0  1993yCat.3135....0C
2216
     SP_TYPE           SP_BIBCODE
2316      A7  1995A&AS..110..367N
2317
2318
     SP_TYPE           SP_BIBCODE
2316      A7  1995A&AS..110..367N
2317
2318
     SP_TYPE           SP_BIBCODE
2333      A2  1993yCat.3135....0C
2334
2335
     SP_TYPE           SP_BIBCODE
2333      A2  1993yCat.3135....0C
2334
2335
     SP_TYPE SP_BIBCODE
2336      F5
2337
     SP_TYPE           SP_BIBCODE
2357      A3  1993yCat.3135....0C
2358
     SP_TYPE           SP_BIBCODE
2361      B8  1995A&AS..110..367N
2362
     SP_TYPE           SP_BIBCODE
2390      A3  1993yCat.3135....0C
2391
2392
     SP_TYPE           SP_BIBCODE
2390      A3  1993yCat.3135....0C
2391
2392
     SP_TYPE           SP_BIBCODE
2443      A0  1995A&AS..110..367N
2444
2445
     SP_TYPE           SP_BIBCODE
2443      A0  1995A&AS..110..367N
2444
2445
     SP_TYPE           SP_BIBCODE
2485      A0  1993yCat.3135....0C
2486
     SP_TYPE           SP_BIBCODE
2633      A5  1995A&AS..110..367N
2634
2635
     SP_TYPE           SP_BIBCODE
2633      A5  1995A&AS..110..367N
2634
2635
     SP_TYPE           SP_BIBCODE
2690      A0  1993yCat.3135....0C
2691
     SP_TYPE           SP_BIBCODE
2709      A0  1995A&AS..110..367N
2710
     SP_TYPE           SP_BIBCODE
2720      F5  1995A&AS..110..367N
2721
     SP_TYPE           SP_BIBCODE
2730      F5  1995A&AS..110..367N
2731
     SP_TYPE           SP_BIBCODE
2744      A0  1995A&AS..110..367N
2745
2746
     SP_TYPE           SP_BIBCODE
2744      A0  1995A&AS..110..367N
2745
2746
       SP_TYPE           SP_BIBCODE
2791  B5IV-VSi  2022ApJS..259...63S
2792
2793
       SP_TYPE           SP_BIBCODE
2791  B5IV-VSi  2022ApJS..259...63S
2792
2793
     SP_TYPE           SP_BIBCODE
2830      A0  1995A&AS..110..367N
2831
     SP_TYPE           SP_BIBCODE
2848      A5  1995A&AS..110..367N
2849
2850
     SP_TYPE           SP_BIBCODE
2848      A5  1995A&AS..110..367N
2849
2850
     SP_TYPE           SP_BIBCODE
2862      A0  1993yCat.3135....0C
2863
2864
     SP_TYPE           SP_BIBCODE
2862      A0  1993yCat.3135....0C
2863
2864
     SP_TYPE           SP_BIBCODE
2875      A2  1995A&AS..110..367N
2876
2877
     SP_TYPE           SP_BIBCODE
2875      A2  1995A&AS..110..367N
2876
2877
     SP_TYPE           SP_BIBCODE
2921       A  1995A&AS..110..367N
2922
2923
     SP_TYPE           SP_BIBCODE
2921       A  1995A&AS..110..367N
2922
2923
     SP_TYPE           SP_BIBCODE
2959      A0  1995A&AS..110..367N
2960
2961
     SP_TYPE           SP_BIBCODE
2959      A0  1995A&AS..110..367N
2960
2961
     SP_TYPE           SP_BIBCODE
3024      F5  1995A&AS..110..367N
3025
3026
     SP_TYPE           SP_BIBCODE
3024      F5  1995A&AS..110..367N
3025
3026
     SP_TYPE           SP_BIBCODE
3035      F8  1993yCat.3135....0C
3036
     SP_TYPE           SP_BIBCODE
3099      A3  1995A&AS..110..367N
3100
3101
     SP_TYPE           SP_BIBCODE
3099      A3  1995A&AS..110..367N
3100
3101
     SP_TYPE           SP_BIBCODE
3104      B2  1995A&AS..110..367N
3105
3106
     SP_TYPE           SP_BIBCODE
3104      B2  1995A&AS..110..367N
3105
3106
     SP_TYPE           SP_BIBCODE
3149      A0  1993yCat.3135....0C
3150
3151
     SP_TYPE           SP_BIBCODE
3149      A0  1993yCat.3135....0C
3150
3151
     SP_TYPE           SP_BIBCODE
3229      F8  1993yCat.3135....0C
3230
     SP_TYPE           SP_BIBCODE
3232      A3  1995A&AS..110..367N
3233
     SP_TYPE           SP_BIBCODE
3290      A2  1995A&AS..110..367N
3291
3292
     SP_TYPE           SP_BIBCODE
3290      A2  1995A&AS..110..367N
3291
3292
     SP_TYPE           SP_BIBCODE
3335      F0  1995A&AS..110..367N
3336
3337
     SP_TYPE           SP_BIBCODE
3335      F0  1995A&AS..110..367N
3336
3337
     SP_TYPE           SP_BIBCODE
3346      F5  1995A&AS..110..367N
3347
3348
     SP_TYPE           SP_BIBCODE
3346      F5  1995A&AS..110..367N
3347
3348
     SP_TYPE           SP_BIBCODE
3492      B8  1993yCat.3135....0C
3493
     SP_TYPE SP_BIBCODE
3592   B1.5V
3593
     SP_TYPE           SP_BIBCODE
3743      A2  1993yCat.3135....0C
3744
     SP_TYPE           SP_BIBCODE
3824      A0  1993yCat.3135....0C
3825
     SP_TYPE           SP_BIBCODE
3980       A  1993yCat.3135....0C
3981
     SP_TYPE           SP_BIBCODE
4021      A0  1993yCat.3135....0C
4022
     SP_TYPE SP_BIBCODE
4112      B8
4113
     SP_TYPE           SP_BIBCODE
4172      F0  1993yCat.3135....0C
4173
     SP_TYPE SP_BIBCODE
4202      F0
4203
4204
     SP_TYPE SP_BIBCODE
4202      F0
4203
4204
     SP_TYPE           SP_BIBCODE
4267      F8  1993yCat.3135....0C
4268
4269
     SP_TYPE           SP_BIBCODE
4267      F8  1993yCat.3135....0C
4268
4269
     SP_TYPE SP_BIBCODE
4286      B5
4287
4288
     SP_TYPE SP_BIBCODE
4286      B5
4287
4288
     SP_TYPE SP_BIBCODE
4326      A2
4327
4328
     SP_TYPE SP_BIBCODE
4326      A2
4327
4328
     SP_TYPE SP_BIBCODE
4339      F5
4340
     SP_TYPE           SP_BIBCODE
4362      A2  1993yCat.3135....0C
4363
     SP_TYPE           SP_BIBCODE
4394       A  1993yCat.3135....0C
4395
     SP_TYPE SP_BIBCODE
4403      F2
4404
4405
     SP_TYPE SP_BIBCODE
4403      F2
4404
4405
     SP_TYPE SP_BIBCODE
4425      F5
4426
     SP_TYPE SP_BIBCODE
4435      A2
4436
4437
     SP_TYPE SP_BIBCODE
4435      A2
4436
4437
     SP_TYPE           SP_BIBCODE
4495      B9  1993yCat.3135....0C
4496
     SP_TYPE           SP_BIBCODE
4534      G0  1993yCat.3135....0C
4535
4536
     SP_TYPE           SP_BIBCODE
4534      G0  1993yCat.3135....0C
4535
4536
     SP_TYPE SP_BIBCODE
4570      F0
4571
     SP_TYPE SP_BIBCODE
4651      A0
4652
     SP_TYPE           SP_BIBCODE
4700      A2  1993yCat.3135....0C
4701
     SP_TYPE           SP_BIBCODE
4725      F5  1993yCat.3135....0C
4726
     SP_TYPE SP_BIBCODE
4747      A2
4748
4749
     SP_TYPE SP_BIBCODE
4747      A2
4748
4749
     SP_TYPE           SP_BIBCODE
4775       A  1993yCat.3135....0C
4776
     SP_TYPE SP_BIBCODE
4927      A5
4928
     SP_TYPE SP_BIBCODE
5042      A0
5043
5044
     SP_TYPE SP_BIBCODE
5042      A0
5043
5044
     SP_TYPE           SP_BIBCODE
5091      A0  1993yCat.3135....0C
5092
     SP_TYPE           SP_BIBCODE
5226      A0  1993yCat.3135....0C
5227
     SP_TYPE           SP_BIBCODE
5248      A0  1993yCat.3135....0C
5249
5250
     SP_TYPE           SP_BIBCODE
5248      A0  1993yCat.3135....0C
5249
5250
     SP_TYPE           SP_BIBCODE
5344      A2  1993yCat.3135....0C
5345
     SP_TYPE           SP_BIBCODE
5408      A2  1993yCat.3135....0C
5409
     SP_TYPE SP_BIBCODE
5474      B8
5475
     SP_TYPE           SP_BIBCODE
5493      A0  1993yCat.3135....0C
5494
5495
     SP_TYPE           SP_BIBCODE
5493      A0  1993yCat.3135....0C
5494
5495
     SP_TYPE           SP_BIBCODE
5540    B0Ib  2022ApJ...937..110L
5541
     SP_TYPE           SP_BIBCODE
5609   B1.5V  2010ApJS..186..191C
5610
     SP_TYPE           SP_BIBCODE
5637      B9  1993yCat.3135....0C
5638
     SP_TYPE           SP_BIBCODE
5663   F0.8V  2010ApJS..186..191C
5664
     SP_TYPE           SP_BIBCODE
5744   B2.8V  2010ApJS..186..191C
5745
     SP_TYPE           SP_BIBCODE
5831      A2  1993yCat.3135....0C
5832
     SP_TYPE           SP_BIBCODE
5891      A0  1993yCat.3135....0C
5892
     SP_TYPE           SP_BIBCODE
5899      B9  1993yCat.3135....0C
5900
     SP_TYPE           SP_BIBCODE
5909      B0  1953IzKry..10..104B
5910
     SP_TYPE           SP_BIBCODE
5968      A0  1993yCat.3135....0C
5969
5970
     SP_TYPE           SP_BIBCODE
5968      A0  1993yCat.3135....0C
5969
5970
     SP_TYPE           SP_BIBCODE
5994      A0  1993yCat.3135....0C
5995
     SP_TYPE           SP_BIBCODE
6127      A0  1993yCat.3135....0C
6128
6129
     SP_TYPE           SP_BIBCODE
6127      A0  1993yCat.3135....0C
6128
6129
     SP_TYPE           SP_BIBCODE
6173      A2  1993yCat.3135....0C
6174
6175
     SP_TYPE           SP_BIBCODE
6173      A2  1993yCat.3135....0C
6174
6175

In [75]:
obj_rep=table[table.duplicated(subset='SCRIPT_NUMBER_ID')==True]['SCRIPT_NUMBER_ID'].values
len(np.unique(obj_rep))

110

We queried Simbad with 2arsec, and inspected objects with two counterparts or more in this radius (110 objects). For all cases at least one of the counterparts did not have a reference for the spectral type or spectral type at all and therefore we discarded them from any further analysis

In [79]:
tableNR=table.drop_duplicates(subset='SCRIPT_NUMBER_ID',keep=False)

In [81]:
tableNR.shape

(5946, 39)

In [83]:
np.sum(tableNR['SP_BIBCODE'].values=='')

904

In [90]:
tableNR.groupby(['SP_BIBCODE']).count()['MAIN_ID'].sort_values()

SP_BIBCODE
2010A&A...515A..16S       1
2008ApJ...672..558C       1
2009A&A...495..121M       1
2009ApJ...695...75H       1
2010A&A...516A..35H       1
                       ...
2008AJ....135..564B     264
2020ApJS..249....3A     274
                        904
1995A&AS..110..367N    1490
1993yCat.3135....0C    2182
Name: MAIN_ID, Length: 92, dtype: int64

In [91]:
(904+1490+2182)/5946

0.7695930036999664

In [26]:
test=df_2[0:6000]

In [27]:
Simbad.add_votable_fields('sptype')
Simbad.add_votable_fields('sp_bibcode')
coordinates = SkyCoord(test[["ra","dec"]].values,unit=("deg","deg"))
tab = Simbad.query_region(coordinates, radius=radius*u.arcsec)

In [28]:
test2=df_2[6000:]
coordinates = SkyCoord(test2[["ra","dec"]].values,unit=("deg","deg"))
tab2 = Simbad.query_region(coordinates, radius=radius*u.arcsec)

In [30]:
tabla=vstack([tab, tab2])

WARNING: MergeConflictWarning: Cannot merge meta key 'description' types <class 'str'> and <class 'str'>, choosing description='Simbad script executed on 2024.06.25CEST17:29:27' [astropy.utils.metadata]

In [31]:
tabla

<Table length=12368>
         MAIN_ID                RA      ... SCRIPT_NUMBER_ID
                             "h:m:s"    ...
          object              str13     ...      int32
------------------------- ------------- ... ----------------
            EC 21086-8739 21 28 07.0677 ...                1
            EC 03379-8354 03 32 14.6120 ...                2
             CPD-82   801 20 20 20.5286 ...                3
            EC 23073-7751 23 11 01.3018 ...                4
                V* AE Oct 20 22 55.2378 ...                5
            EC 04002-7554 03 58 57.3037 ...                6
                      ...           ... ...              ...
              V* V462 Cep 23 51 49.6549 ...             6051
[WWV2004] J1550242+821007 15 50 24.9214 ...             6052
                HD  23276 03 58 19.5566 ...             6053
                HD  79125 09 24 19.3578 ...             6054
                HD  21537 03 43 30.1193 ...             6055
 SDSS J082901.99+842726.2 08 29 02.0399 ...             6056

In [35]:
tabla['SCRIPT_NUMBER_ID']

<MaskedColumn name='SCRIPT_NUMBER_ID' dtype='int32' length=12368>
   1
   2
   3
   4
   5
   6
   7
   8
   9
 ...
6049
6050
6051
6052
6053
6054
6055
6056

In [34]:
Simbad.query_region?

In [21]:
np.sum(tab['SP_BIBCODE'].value=='1974A&AS...16..277C')

11

In [22]:
np.sum(tab['SP_BIBCODE'].value=='')

14

In [11]:
test

,source_id,ra,dec,ra_error,dec_error,parallax,parallax_error,parallax_over_error,pmra,pmdec,...,R_x,J,H,K,u,g,r_xa,i,z,angDist
0,6341936069186773888,322.029689,-87.451542,0.014296,0.016214,0.061743,0.018665,3.307911,2.399615,-5.225902,...,14.489,14.187,14.238,14.337,NaN,14.242,14.337,NaN,NaN,0.092008
1,4615556475452740480,53.061042,-83.736951,0.016101,0.016573,0.046835,0.017140,2.732576,3.895391,2.275492,...,14.375,14.340,14.332,14.381,NaN,14.058,14.251,14.482,NaN,0.072181
2,6348968408118750208,305.085692,-82.427702,0.009958,0.010758,0.837793,0.012066,69.435165,4.614924,-8.705492,...,NaN,10.080,9.876,9.788,NaN,NaN,NaN,NaN,NaN,0.157649
3,6354071482101259648,347.755530,-77.583660,0.018343,0.020622,0.117265,0.021830,5.371705,5.113016,-2.043968,...,NaN,14.383,14.336,14.120,NaN,NaN,NaN,NaN,NaN,0.088103
4,6363504054917758592,305.730093,-76.068019,0.009825,0.011417,0.232584,0.013630,17.064213,-3.499222,-3.919243,...,NaN,12.770,12.571,12.506,NaN,NaN,NaN,NaN,NaN,0.084065
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,3132997570911033984,103.681461,7.027954,0.017873,0.017061,1.750222,0.021325,82.074230,-1.634334,-2.223650,...,NaN,8.776,8.765,8.724,NaN,NaN,NaN,NaN,NaN,0.044154
5996,4297132032545725056,299.629678,7.031396,0.362252,0.301926,0.773246,0.535641,1.443591,-0.622325,-5.720377,...,NaN,10.065,10.135,10.026,NaN,NaN,NaN,NaN,NaN,0.092066
5997,3153780741558513280,105.596462,7.035489,0.030995,0.027926,1.333713,0.033379,39.956380,-1.599291,-1.653234,...,NaN,8.667,8.736,8.708,NaN,NaN,NaN,NaN,NaN,0.036803
5998,3322161296563994752,92.282647,7.055391,0.027482,0.032031,2.025231,0.037520,53.977497,0.245061,-5.204969,...,NaN,8.362,8.365,8.322,NaN,NaN,NaN,NaN,NaN,0.083372
5999,4487067099955734400,261.985668,7.058510,0.019142,0.016838,0.104301,0.025561,4.080513,-3.227060,-8.289150,...,NaN,14.828,14.844,14.867,16.178,15.006,15.193,15.348,15.422,0.142323

In [12]:
Simbad.add_votable_fields('sptype')
Simbad.add_votable_fields('sp_bibcode')
coordinates = SkyCoord(test[["ra","dec"]].values,unit=("deg","deg"))
tab = Simbad.query_region(coordinates, radius=radius*u.arcsec)

ReadTimeout: HTTPConnectionPool(host='simbad.u-strasbg.fr', port=80): Read timed out. (read timeout=60)

In [ ]:
test2=df_2[6000:]
coordinates = SkyCoord(test2[["ra","dec"]].values,unit=("deg","deg"))
tab2 = Simbad.query_region(coordinates, radius=radius*u.arcsec)

In [6]:
Simbad.list_votable_fields()

--NOTES--

1. The parameter filtername must correspond to an existing filter. Filters include: B,V,R,I,J,K.  They are checked by SIMBAD but not astroquery.simbad

2. Fields beginning with rvz display the data as it is in the database. Fields beginning with rv force the display as a radial velocity. Fields beginning with z force the display as a redshift

3. For each measurement catalog, the VOTable contains all fields of the first measurement. When applicable, the first measurement is the mean one.

Available VOTABLE fields:

bibcodelist(y1-y2)
biblio
cel
cl.g
coo(opt)
coo_bibcode
coo_err_angle
coo_err_maja
coo_err_mina
coo_qual
coo_wavelength
coordinates
dec(opt)
dec_prec
diameter
dim
dim_angle
dim_bibcode
dim_incl
dim_majaxis
dim_minaxis
dim_qual
dim_wavelength
dimensions
distance
distance_result
einstein
fe_h
flux(filtername)
flux_bibcode(filtername)
flux_error(filtername)
flux_name(filtername)
flux_qual(filtername)
flux_system(filtername)
flux_unit(filtername)
fluxdata(filtername)
gcrv
gen
gj
hbet
hbet1
hgam
id(opt)
ids
iras
irc
iso
iue
jp11
link_bibcode
main_id
measurements
membership
mesplx
mespm
mk
morphtype
mt
mt_bibcode
mt_qual
otype
otype(opt)
otypes
parallax
plx
plx_bibcode
plx_error
plx_prec
plx_qual
pm
pm_bibcode
pm_err_angle
pm_err_maja
pm_err_mina
pm_qual
pmdec
pmdec_prec
pmra
pmra_prec
pos
posa
propermotions
ra(opt)
ra_prec
rot
rv_value
rvz_bibcode
rvz_error
rvz_qual
rvz_radvel
rvz_type
rvz_wavelength
sao
sp
sp_bibcode
sp_nature
sp_qual
sptype
td1
typed_id
ubv
uvby
uvby1
v*
velocity
xmm
z_value
For more information on a field:
Simbad.get_field_description ('field_name')
Currently active VOTABLE fields:
 ['main_id', 'coordinates', 'sptype']